doc: update installation.md for third_party packages
facebookarchive/caffe2 pull request #1724
Opened 2018-01-10 01:25 UTC by leemgs

PR Description
-----------------

This commit informs the developers why they have to use packages of third_party
folder instead of packages in their Linux distribution.

By default, Caffe2 find installed packages in the Linux distribution. If it
cannot be found, as a next step Caffe2 uses the version bundled in third_party folder.

**Changes proposed in this PR:**
1. Added difference between Linux distro packages and third_party packages

**Self assessment:**
Checked.

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

2018-01-10 01:27 UTC, leemgs commented
> https://github.com/caffe2/caffe2/pull/1698#issuecomment-356350649

@pietern PTAL, Could you reveiw this PR if this proposal is meaningful/helpful to the developers that are compling Caffe2 from source in their Linux distribution?

2018-01-24 22:09 UTC, orionr requested changes
Hi @leemgs - apologies for the slow response on this. Can you make the above wording changes? After that I'll bring it in. Thanks!

2018-01-25 06:43 UTC, leemgs commented on docs/installation.md
> +Note that you need to uninstall the packages due to a runtime dependency and potential bug issues if you already installed Eigen and pybind11 package in your Linux distribution. Because packages of s
@orionr , Applied. Then re-submitted PR with squash. Thanks.

2018-01-25 17:00 UTC, orionr approved these changes

2018-01-25 22:33 UTC, closed without merging