[WIP] fp16 training
facebookarchive/caffe2 pull request #606
Opened 2017-05-18 20:34 UTC by slayton58

fp16 parameter initialization for convolution, FC
Map of low precision param -> high precision copy
Example of fp16 training in CIFAR10

2017-05-22 02:11 UTC, asaadaldien commented on caffe2/python/data_parallel_model.py
> +    # if in a multi-precision environment, make sure that the broadcast parameters
Move this to a method _UpdateFloatCopies for example?

2017-05-22 05:56 UTC, asaadaldien requested changes

2017-05-22 05:56 UTC, asaadaldien commented on caffe2/python/examples/cifar10_fp16.py
> +    data, label = model.ImageInput(
`brew.image_input(model,....` ?

2017-05-22 05:56 UTC, asaadaldien commented on caffe2/python/examples/cifar10_fp16.py
> +        conv1 = brew.conv(model, data, 'conv1', 3, 32, 5,
Please use max 80 character / line lint rule in this file.

2017-05-22 05:56 UTC, asaadaldien commented on caffe2/python/examples/cifar10_fp16.py
> +    print("adding gradient ops")
Please use logging with debugging verbosity level (logger.info) instead of prints.

2017-05-22 05:56 UTC, asaadaldien commented on caffe2/python/examples/cifar10_fp16.py
> +        # AddBookkeepingOperators(train_model)
Remove uncommented line.

2017-05-22 05:56 UTC, asaadaldien commented on caffe2/python/examples/cifar10_fp16.py
> +    train_model.net.Proto().type = 'dag'
Consider setting network type and num_workers as a command line input arguments.

2017-05-22 05:56 UTC, asaadaldien commented on caffe2/python/examples/cifar10_fp16.py
> +    with core.DeviceScope(core.DeviceOption(caffe2_pb2.CUDA, 0)):
This example will work only on GPU. Why not having device as a command line input argument so users  can run it on both CPU & GPU (HalfToFloat & FloaToHalf has CPU/CUDA implementations).

2017-05-22 13:08 UTC, slayton58 commented
I've updated data_parallel_model.py based on your comments, the cifar10 code was intended to be an example of how to use those additions to train in fp16. If you want it to actually be included I can fix it up based on your comments, but that wasn't the original intention.

2017-05-22 14:07 UTC, slayton58 commented on caffe2/python/examples/cifar10_fp16.py
> +        conv1 = brew.conv(model, data, 'conv1', 3, 32, 5,
What is the line lint rule? I don't see any utilities supplied with the code for me to lint myself...

2017-05-22 14:55 UTC, slayton58 commented on caffe2/python/examples/cifar10_fp16.py
> +    with core.DeviceScope(core.DeviceOption(caffe2_pb2.CUDA, 0)):
This is explicitly a GPU test. AFAIK CPU operators don't have any fp16 implementations.

2017-05-22 18:37 UTC, salexspb requested changes

2017-05-22 18:37 UTC, salexspb commented on caffe2/python/examples/cifar10_fp16.py
> +    ITER = brew.iter(model, "ITER")
why not use optimizers.py  instead of this hardcoded procedure?

2017-05-22 18:37 UTC, salexspb commented on caffe2/python/model_helper.py
> +        self.param_to_float_copy = {}
this doesn't seem to be very generic to put into the main modeling class and then having all the optimizers and modeling helpers access it... You also have quite a bit of copy paste in each of the helpers (fc and conv in this case)
Seems like you just need to have some metadata on parameters. There is a ParamterInfo class, but we are rethinking it right now. Parameters can have a bunch of things associated with them. Including optimizer specific information which seems you need here.


Another approach I thought of is that if BlobReference has some info  of  anticipated type of the blob. Then you could even automatically insert conversions to and from fp16 when operations like MomentumSGD are called. 

I would like to chat with Andrey Malevich from our team who is working on new parameter abstractions for ModelHelper class and see if this kind of info fits into his new stuff.

2017-06-08 20:09 UTC, slayton58 commented
This work was done in a different way and merge, closing.

2017-06-08 20:09 UTC, closed without merging