A simple tutorial for C++ users
facebookarchive/caffe2 pull request #780
Opened 2017-06-11 11:15 UTC by HWhale

I'm the one who usually use C++, and I found that the tutorials for users who use C++ aren't enough. Especially there are some questions which ask how to start Caffe2 with C++.

So I made a simplest tutorial. It's a very simple document but I think it may can help some C++ users. Please check my pull request and leave your feedback. I'll check it.

2017-06-14 18:33 UTC, salexspb commented
Looks like this is Windows specific. Aaron, could you check how to make sure it fits best in the website?

2017-06-19 19:36 UTC, aaronmarkham requested changes
Can you move line 6 for the nav to the bottom of the tutorials section? (After   - id: sync-sgd)

Really minor nit: please upper-case anytime you use Caffe2. (lines 9, 21, and 24 in the md file) 

Thanks a lot for doing this tutorial!

2017-06-22 21:17 UTC, aaronmarkham approved these changes

2017-06-22 21:17 UTC, merged

2017-06-22 21:18 UTC, aaronmarkham commented
Thank you @HWhale !!!